from random import choice as rc

places = [
    "park",
    "restaurant",
    "movie theater",
    "marina",
    "bike trail",
    "hiking trail",
    "adult bookstore",
    "brothel",
    "Chuck E. Cheese",
    "opium den",
    "crackhouse",
    "firing range",
    "mall food court",
    "cemetery",
    "city dump",
    "children's hospital",
    "dog park",
]

family_relationships = [
    "mother",
    "father",
    "sister",
    "brother",
    "grandmother",
    "grandfather",
    "aunt",
    "uncle",
    "cousin",
    "niece",
    "nephew",
    "daughter",
    "son",
    "wife",
    "husband",
    "partner",
    "stepmother",
    "stepfather",
    "stepsister",
    "stepbrother",
    "half-sister",
    "half-brother",
]

us_presidents_1800s = [
    "John Adams",
    "Thomas Jefferson",
    "James Madison",
    "James Monroe",
    "John Quincy Adams",
    "Andrew Jackson",
    "Martin Van Buren",
    "William Henry Harrison",
    "John Tyler",
    "James K. Polk",
    "Zachary Taylor",
    "Millard Fillmore",
    "Franklin Pierce",
    "James Buchanan",
]


ralph_items = [
    "sawdust",
    "cockroaches",
    "sharts",
    "farts",
    "dead mice",
    "toenail clippings",
    "Confederate currency",
    "hair",
    "dog turds",
    "rat feces",
    "frozen corndogs",
    "sporks",
    "goddamn bananas",
    "dildos",
    "urine",
    "filth",
    "hobo teeth",
    "horse urine",
    "dicks",
    "anal beads",
    "moldy sausage",
    "pencil shavings",
    "pubes",
    "uranium",
    "radium",
    "asbestos",
]

old_barn_items = [
    "hay",
    "rusty tools",
    "tractor parts",
    "animal feed",
    "wood planks",
    "mason jars",
    "old furniture",
    "tattered blankets",
    "barbed wire",
    "wagon wheels",
    "broken glass",
    "horse saddles",
    "oil lamps",
    "grain sacks",
]

hospital_items = [
    "stethoscope",
    "syringe",
    "oxygen tank",
    "IV drip",
    "defibrillator",
    "wheelchair",
    "crutches",
    "bedpan",
    "urinal",
    "gurney",
    "patient gown",
    "scrubs",
    "surgical instruments",
    "CT scanner",
    "lab coats",
    "sterile gloves",
    "masks",
    "disinfectants",
    "antibiotics",
    "painkillers",
    "antidepressants",
    "sleep aids",
    "blood bags",
    "medical waste containers",
    "biohazard suits",
    "ventilator",
    "suction machine",
    "nebulizer",
    "hearing aid",
    "dental floss",
    "toothbrush",
    "hand sanitizer",
    "sanitary wipes",
]

medieval_weapons = [
    "Sword",
    "Longbow",
    "Crossbow",
    "Mace",
    "War hammer",
    "Lance",
    "Halberd",
    "Battle axe",
    "Flail",
    "Morning star",
    "Poleaxe",
    "Dagger",
    "Rapier",
    "Scimitar",
    "Falchion",
    "Greatsword",
    "Trident",
]

us_presidents_1800s = [
    "John Adams",
    "Thomas Jefferson",
    "James Madison",
    "James Monroe",
    "John Quincy Adams",
    "Andrew Jackson",
    "Martin Van Buren",
    "William Henry Harrison",
    "John Tyler",
    "James K. Polk",
    "Zachary Taylor",
    "Millard Fillmore",
    "Franklin Pierce",
    "James Buchanan",
]

badthings = [
    "sonofabitch",
    "Satanism",
    "Voodoo",
    "human sacrifice",
    "blood rituals",
    "sexually transmitted disease",
    "malice",
    "butt demons",
    "sharts",
    "syphilis",
    "herald of the damned",
    "filthspawn",
    "witchcraft",
    "Asmodeus",
    "filth",
    "dookie puddles",
    "profane rites",
    "Flop Shoggoth",
    "Diaper Christ",
    "Turd Prophet",
    "turpentine enema",
    "rectal elephantitis",
    "gonorrhea",
    "herpes",
    "volcanic diarrhea",
    "abberation",
    "abomination",
    "fetid flatulence",
    "steaming diarrhea dump",
    "soiled undies",
    "depravity",
]

emotions = [
    "fear",
    "contempt",
    "anger",
    "disgust",
    "revulsion",
    "fury",
    "rage",
    "outrage",
    "horror",
    "condescension",
    "repulsion",
    "hatred",
    "antipathy",
    "loathing",
    "ire",
    "indignation"
]

cleaning_items = [
    "dish soap",
    "all-purpose cleaner",
    "glass cleaner",
    "baking soda",
    "vinegar",
    "lemon juice",
    "rubbing alcohol",
    "ammonia",
    "broom",
    "mop",
    "duster",
    "sponge",
    "paper towels",
    "dung",
    "diarrhea",
]

industrial_solvents = ['acetone', 'benzene', 'chloroform', 'dimethylformamide', 'ethyl acetate', 'hexane', 'isopropyl alcohol', 'methyl ethyl ketone', 'toluene', 'xylene']


folk_sayings = [
    "A penny saved is a penny earned.",
    "Actions speak louder than words.",
    "All's fair in love and war.",
    "An apple a day keeps the doctor away.",
    "Better late than never.",
    "Don't count your chickens before they hatch.",
    "Every cloud has a silver lining.",
    "Honesty is the best policy.",
    "If at first you don't succeed, try, try again.",
    "Laughter is the best medicine.",
    "Practice makes perfect.",
    "The early bird catches the worm.",
    "The grass is always greener on the other side.",
    "Time heals all wounds.",
    "When in Rome, do as the Romans do.",
    "You can lead a horse to water, but you can't make it drink.",
    "You reap what you sow.",
]


mythical_creatures = [
    "Dragon",
    "Unicorn",
    "Mermaid",
    "Griffin",
    "Minotaur",
    "Centaur",
    "Sphinx",
    "Phoenix",
    "Kraken",
    "Chimera",
    "Pegasus",
    "Chuck Norris",
    "Yeti",
    "Siren",
    "Gorgon",
    "Hippogriff",
    "Werewolf",
    "Satyr",
]

dead_celebs = [
    "John Ritter",
    "John Denver",
    "Joan Rivers",
    "Sean Connery",
    "Milton Berle",
    "Don Rickles",
    "Errol Flynn",
    "Soupy Sales",
    "Ronald Reagan",
]

warnerbros = [
    "Bugs Bunny",
    "Daffy Duck",
    "Tweety Bird",
    "Sylvester the Cat",
    "Road Runner",
    "Wile E. Coyote",
    "Porky Pig",
    "Elmer Fudd",
    "Yosemite Sam",
    "Foghorn Leghorn",
    "Marvin the Martian",
    "Pepe Le Pew",
    "Speedy Gonzales",
    "The Tasmanian Devil",
    "Michigan J. Frog",
    'Tom and Jerry',
    'Scooby-Doo',
    'Pikachu',
    'Bart Simpson',
    'SpongeBob SquarePants',
    'Hello Kitty',
]

mental_illnesses = [
    "Depression",
    "Alien Hand Syndrome",
    "Cotard Delusion",
    "Clinical Lycanthropy",
    "Diogenes Syndrome",
    "Schizophrenia",
    "Dementia",
    "Dissociative Identity Disorder",
    "Capgras Delusion",
    "Priapism",
    "Anal Warts",
    "Halitosis",
    "Uncontrollable Flatulence",
    "Volcanic Diarrhea",
    "Pyromania",
    "Necrophilia",
    "Cannibalism",
    "Delusions Of Grandeur",
    "Psychopathy",
    "Sociopathy",
    "Uncontrolled Sharting",
    "Kleptomania",
    "Illiteracy",
    "Irritable Bowel Syndrome",
    "Rectal Elephantitis",
    "Persistent Anal Leakage",
]


extinct = [
    "Dodo",
    "Great Auk",
    "Tasmanian Tiger",
    "Mammoth",
    "Sabre-toothed Cat",
    "Woolly Rhino",
    "Steller's Sea Cow",
    "Passenger Pigeon",
    "Quagga",
    "Irish Elk",
    "Haast's Eagle",
    "Thylacine",
    "Glyptodon",
    "Japanese Sea Lion",
    "Caribbean Monk Seal",
    "Pyrenean Ibex",
    "Baiji Dolphin",
    "Golden Toad",
    "Western Black Rhinoceros",
    "Formosan Clouded Leopard",
    "Javan Tiger",
    "Giant Tortoise",
    "Eastern Cougar",
    "Cape Lion",
    "Caspian Tiger",
    "Dusky Seaside Sparrow",
    "Toolache Wallaby",
    "Tecopa Pupfish",
    "Catarina Pupfish",
    "Zanzibar Leopard",
    "Bubal Hartebeest",
    "Mexican Grizzly Bear",
    "Honshu Wolf",
    "Saudi Gazelle",
    "Cape Verde Giant Skink",
    "Cape Verde Giant Gecko",
    "Guam Flying Fox",
    "Santa Cruz Pupfish",
    "Guadalupe Caracara",
    "Tahitian Sandpiper",
    "Desert Rat-kangaroo",
    "Tasmanian Bettong",
    "Heath Hen",
    "Ascension Island Rail",
    "Ascension Island Thrush",
    "Guam Flying Fox",
]


extinct_animals = [
    "Tasmanian Tiger",
    "Dodo",
    "Great Auk",
    "Passenger Pigeon",
    "Quagga",
    "Pyrenean Ibex",
    "Caribbean Monk Seal",
    "Japanese Sea Lion",
    "Baiji Dolphin",
    "Western Black Rhinoceros",
    "Thylacine",
    "Steller’s Sea Cow",
    "Aurochs",
    "Caspian Tiger",
    "Heath Hen",
    "Laughing Owl",
    "Eastern Hare Wallaby",
    "Golden Toad",
    "Atitlán Grebe",
    "Toolache Wallaby",
    "Pinta Island Tortoise",
    "Tecopa Pupfish",
    "Dusky Seaside Sparrow",
    "Round Island Burrowing Boa",
    "Jamaican Petrel",
    "Liverpool Pigeon",
    "Ascension Island Shag",
]

preslist = [
    "George Washington",
    "John Adams",
    "Thomas Jefferson",
    "James Madison",
    "James Monroe",
    "John Quincy Adams",
    "Andrew Jackson",
    "Martin Van Buren",
    "William Henry Harrison",
    "John Tyler",
    "James K. Polk",
    "Zachary Taylor",
    "Millard Fillmore",
    "Franklin Pierce",
    "James Buchanan",
    "Abraham Lincoln",
    "Andrew Johnson",
    "Ulysses S. Grant",
    "Rutherford B. Hayes",
    "James A. Garfield",
    "Chester A. Arthur",
    "Grover Cleveland",
    "Benjamin Harrison",
    "William McKinley",
    "Theodore Roosevelt",
    "William Howard Taft",
    "Woodrow Wilson",
    "Warren G. Harding",
    "Calvin Coolidge",
    "Herbert Hoover",
    "Franklin D. Roosevelt",
    "Harry S. Truman",
    "Dwight D. Eisenhower",
    "John F. Kennedy",
    "Lyndon B. Johnson",
    "Richard Nixon",
    "Gerald Ford",
    "Jimmy Carter",
    "Ronald Reagan",
    "George H. W. Bush",
    "Bill Clinton",
    "George W. Bush",
    "Barack Obama",
    "Donald Trump",
    "Joe Biden",
]


gardening_tools = [
    "shovel",
    "rake",
    "hoe",
    "trowel",
    "pruning shears",
    "wheelbarrow",
    "watering can",
    "sprinkler",
    "hose",
    "fork",
    "weed puller",
    "lawn mower",
    "hedge trimmer",
    "leaf blower",
    "garden scissors",
    "soil rake",
    "spade",
    "pruning saw",
    "garden hose nozzle",
]

fantasy_characters = [
    "wizard",
    "witch",
    "goblin",
    "sorcerer",
    "warlock",
    "dragon",
    "elf",
    "dwarf",
    "orc",
    "goblin",
    "troll",
    "centaur",
    "mermaid",
    "fairy",
    "ghost",
    "vampire",
    "werewolf",
    "zombie",
    "necromancer",
    "minotaur",
    "griffin",
    "cyclops",
    "medusa",
    "Chuck Norris",
    "chimera",
    "kraken",
    "harpy",
    "golem",
]

tv_shows_1970s = ['All in the Family', 'M*A*S*H', 'Happy Days', 'The Mary Tyler Moore Show', 'The Waltons', 'The Jeffersons', 'The Love Boat', 'Three\'s Company', 'Good Times', 'The Brady Bunch', 'Charlie\'s Angels', 'Little House on the Prairie', 'The Six Million Dollar Man', 'Baretta', 'Kojak', 'The Rockford Files', 'Starsky & Hutch', 'Emergency!', 'The Dukes of Hazzard', 'Welcome Back, Kotter', 'Family Matters', 'Saved By The Bell', 'Full House']

cleaning_fluids = [
    "Bleach",
    "Ammonia",
    "Vinegar",
    "Rubbing alcohol",
    "Hydrogen peroxide",
    "Dish soap",
    "Laundry detergent",
    "Window cleaner",
    "Furniture polish",
    "Carpet cleaner",
    "All-purpose cleaner",
    "Toilet bowl cleaner",
    "Drain cleaner",
    "Oven cleaner",
]

states = [
    "Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "Florida",
    "Georgia",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming",
]

planets = ["Mercury", "Venus", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune","Pluto"]

rodents = ['Mouse', 'Rat', 'Hamster', 'Gerbil', 'Guinea Pig', 'Chinchilla', 'Squirrel', 'Beaver', 'Capybara', 'Porcupine', 'Muskrat', 'Vole', 'Marmot', 'Groundhog', 'Prairie Dog', 'Cane Rat', 'Mole Rat']


softrock = [
    "10cc",
    "Bryan Adams",
    "Air Supply",
    "The Alan Parsons Project",
    "Paul Anka",
    "The Association",
    "Atlanta Rhythm Section",
    "Bee Gees",
    "Michael Bolton",
    "Debby Boone",
    "Boston",
    "Bread",
    "Jackson Browne",
    "Peabo Bryson",
    "Glen Campbell",
    "Captain & Tennille",
    "Eric Carmen",
    "Kim Carnes",
    "The Carpenters",
    "Harry Chapin",
    "Chicago",
    "Eric Clapton",
    "Joe Cocker",
    "Phil Collins",
    "Jim Croce",
    "Crosby, Stills, Nash & Young",
    "John Denver",
    "Neil Diamond",
    "The Doobie Brothers",
    "Dr. Hook & the Medicine Show",
    "The Eagles",
    "England Dan & John Ford Coley",
    "Roberta Flack",
    "Fleetwood Mac",
    "Dan Fogelberg",
    "Foreigner",
    "Peter Frampton",
    "Genesis",
    "Andy Gibb",
    "Hall & Oates",
    "Janis Ian",
    "Terry Jacks",
    "Jefferson Starship",
    "Billy Joel",
    "Elton John",
    "Robert John",
    "Sammy Johns",
    "Michael Johnson",
    "Journey",
    "Kansas",
    "Carole King",
    "Kenny Loggins",
    "Loggins and Messina",
    "Barry Manilow",
    "Don McLean",
    "Van Morrison",
    "Randy Newman",
    "Olivia Newton-John",
    "Stevie Nicks",
    "Harry Nilsson",
    "REO Speedwagon",
    "Lionel Richie",
    "Seals and Crofts",
    "Bob Seger",
    "Simon & Garfunkel",
    "Carly Simon",
    "Paul Simon",
    "Starland Vocal Band",
    "Steely Dan",
    "Cat Stevens",
    "Rod Stewart",
    "Sting",
    "Styx",
    "James Taylor",
    "Three Dog Night",
    "Toto",
    "Bonnie Tyler",
    "Wings",
    "Steve Winwood",
]

monsters = [
    "Dracula",
    "Frankenstein's monster",
    "The Wolf Man",
    "The Mummy",
    "The Creature from the Black Lagoon",
    "The Phantom of the Opera",
    "The Invisible Man",
    "Godzilla",
    "King Kong",
    "The Blob",
]

italian_dishes = [
    "Spaghetti Carbonara",
    "Margherita Pizza",
    "Lasagna",
    "Fettuccine Alfredo",
    "Risotto",
    "Osso Buco",
    "Chicken Parmigiana",
    "Gnocchi",
    "Caprese Salad",
    "Tiramisu",
]

stds = [
    "herpes",
    "gonorrhea",
    "syphilis",
    "anal warts",
    "crabs",
    "lice",
]

randwords = [
    'filth',
    'anus',
    'demon',
    'dung',
    'disease',
    'vomit',
    'fart',
    'penis',
    'diarrhea',
    'flatulence',
    'mildew',
    'rot',
    'plague',
    'desecration',
    'scum',
    'anger',
    'evisceration',
    'diaper',
    'autopsy',
    'dildo',
    'garbage',
    'necrosis',
    'stink',
    'depravity',
]

townprefix = ['fart','poop','crack','dingle','shit','ass','dookie','jizz','wang','dong','weiner','piss',
'butt','diarrhea','anal','dick','toilet','filth','flop','cunt','gape','boner','fuck','stank','plop','dung','crap','crapping', 'dump', 'pork','meat','crust','scrote']

townsuffix = ['burg','ville','ton','shire',' Springs', ' City', 'ham', 'ford', 'stead', 'cester', 'worth', 'mouth']


felonies = [
'Abusive Sexual Contact',
'Advocating Overthrow of Government',
'Aggravated Assault and Battery',
'Aggravated Identity Theft',
'Aiming a Laser Pointer at an Aircraft',
'Airplane Hijacking',
'Armed Robbery',
'Arson',
'Public Intoxication',
'Assassination',
'Assault with a Deadly Weapon',
'Assaulting or Killing a Federal Officer',
'Attempt to commit Murder/Manslaughter',
'Bankruptcy Fraud/Embezzlement',
'Bank Robbery',
'Blackmail',
'Bombing Matters',
'Bond Default',
'Bribery Crimes',
'Check Fraud',
'Civil Action to Restrain Harassment of a Victim or Witness',
'Coercion',
'Commodities Price Fixing',
'Computer Crime',
'Concealing An Escaped Prisoner',
'Concealing Person from Arrest',
'Concealment of Assets',
'Conspiracy to Impede or Injure an Officer',
'Contempt of Court',
'Counterfeiting',
'Counterintelligence Crimes',
'Credit Card Fraud',
'Crime Aboard Aircraft',
'Criminal Contempt of Court',
'Criminal Infringement of a Copyright',
'Cyber Crimes',
'Damage to Religious Property',
'Destruction of Aircraft or Motor Vehicles Used in Foreign Commerce',
'Disclosure of Confidential Information',
'Domestic Terrorism',
'Domestic Violence',
'Drug Trafficking',
'DUI/DWI on Federal Property',
'Economic Espionage',
'Election Law Crimes',
'Embezzlement',
'Embezzlement Against Estate',
'Entering Train to Commit Crime',
'Exportation of Drugs',
'Extortion',
'Failure to Appear on Felony Offense',
'Failure to Pay Legal Child Support Obligations',
'False Statement to Obtain Unemployment Compensation',
'Financial Transactions with Foreign Government',
'First Degree Murder',
'Flight to Avoid Prosecution or Giving Testimony',
'Forced Labor',
'Forgery',
'Fraud Activity in Connection with Electronic Mail',
'Fraud Against the Government',
'Genocide',
'Hacking Crimes',
'Harboring Terrorists',
'Hate Crime Acts',
"Sale Of Horsemeat For Human Consumption",
"Jaywalking",
'Homicide',
'Hostage Taking',
'Identity Theft',
'Illegal Possession of Firearms',
'Impersonating An Officer',
'Insider Trading Crimes',
'Insurance Fraud',
'Interference with the Operation of a Satellite',
'International Parental Kidnapping',
'International Terrorism',
'Larceny',
'Mailing Threatening Communications',
'Major Fraud Against the U.S.',
'Manslaughter',
'Misuse of Passport',
'Misuse of Visas, Permits, or Other Documents',
'Money Laundering',
'Motor Vehicle Theft',
'Murder Committed During a Drug-related Drive-by shooting',
'Murder Committed in a Federal Government Facility',
'Narcotics Violations',
'Obstructing Examination of Financial Institution',
'Obstruction of Criminal Investigations',
'Partial Birth Abortion',
'Perjury',
'Pirating',
'Possession by Restricted Persons',
'Possession of False Papers to Defraud the U.S.',
'Possession of Narcotics',
'Probation Violation',
'Product Tampering',
'Prohibition of Illegal Gambling Businesses',
'Prostitution',
'Protection of Foreign Officials',
'Public Corruption Crimes',
'Racketeering',
'Receiving the Proceeds of Extortion',
'Rescue of Seized Property',
'Retaliating Against a Witness, Victim, or an Informant',
'Robbery',
'Robberies and Burglaries Involving Controlled Substances',
'Sabotage',
'Sale of Citizenship Papers',
'Sale of Stolen Vehicles',
'Searches Without Warrant',
'Second Degree Murder',
'Serial Murders',
'Shoplifting',
'Smuggling',
'Solicitation to Commit a Crime of Violence',
'Stalking In Violation of Restraining Order',
'Stolen Property; Buying, Receiving, or Possessing',
'Subornation of Perjury',
'Suits Against Government Officials',
'Tampering with a Witness, Victim, or Informant',
'Tampering with Consumer Products',
'Tampering with Vessels',
'Theft of Trade Secrets',
'Torture',
'Trafficking in Counterfeit Goods or Services',
'Transportation of Slaves from U.S.',
'Transportation of Stolen Vehicles',
'Transportation of Terrorists',
'Trespassing',
'Treason',
'Unauthorized Removal of Classified Documents',
'Use of Fire or Explosives to Destroy Property',
'Use of Weapons of Mass Destruction',
'Vandalism',
'Video Voyeurism',
'Violation of Prohibitions Governing Atomic Weapons',
'Violence at International airports',
'Willful Wrecking of a Train Resulting in Death',
'Wire Fraud',
]

common_insects = ['ant', 'roach', 'fly', 'mosquito', 'moth', 'spider', 'termite', 'tick', 'wasp', 'leech','beetle','cricket']

common_ailments = ['Headache', 'Common Cold', 'Flu', 'Fever', 'Allergies', 'Asthma', 'Bronchitis', 'Pneumonia', 'Sinusitis', 'Stomach ache', 'Indigestion', 'Constipation', 'Diarrhea', 'Heartburn', 'Acid reflux', 'Urinary tract infection', 'Yeast infection', 'Hemorrhoids', 'Back pain', 'Arthritis', 'Osteoporosis', 'Sprains and strains', 'Insect bites', 'Sunburn','Cirrhosis']

barnyard_animals = ["Cow", "Pig", "Sheep", "Goat", "Horse", "Donkey", "Chicken", "Duck", "Turkey", "Goose"]

measurements = ['teaspoon', 'tablespoon', 'fluid ounce', 'cup', 'pint', 'quart', 'gallon', 'milliliter', 'liter', 'gram', 'ounce', 'pound']

organs = ['brain', 'heart', 'lungs', 'liver', 'stomach', 'intestines', 'kidneys', 'bladder', 'pancreas', 'spleen', 'gallbladder', 'adrenal glands']

natural_disasters = ['earthquake', 'hurricane', 'tornado', 'flood', 'drought', 'wildfire', 'volcano eruption', 'tsunami', 'avalanche', 'landslide', 'sinkhole']

deaths = ['electrocution', 'lethal injection', 'burning alive', 'castration', 'beheading','hanging','drawing and quartering','drowning','live burial', 'forced sodomy', 'fatal enemas', 'dysentery']

genres = ['jizz','meth','flop','shit','horse','dung','lettuce','fart','tard','pube','grope','cyst','polka','foam','diarrhea','fiddle','tuba','flute','anus','urine','ass','weiner','sack','poop']

prefix = [
    "Yung",
    "Meager",
    "Lil",
    "Young",
    "Truncated",
    "Wee",
    "Shriveled",
    "$hort",
    "Undersized",
    "Mister",
    "Yerng",
    "Leel",
    "Yawng",
    "Masta",
    "Uncle",
    "Tiny",
    "Smallish",
    "Lil' Half",
    "Dr.",
    "King",
    "Waka Flaka",
    "Lord",
    "Gucci",
    "A$AP",
    "Yarng",
    "Jung",
    "Yong",
    "Trill",
    "Big",
    "Too",
    "Killer",
    "Gro$$",
]

suffix = [
    "Baby",
    "Stain",
    "Skidmark",
    "Child",
    "Victim",
    "Dookie",
    "Stankdrawers",
    "Man",
    "Mane",
    "Toddler",
    "Fetus",
    "Toilet",
    "Gardener",
    "Infant",
    "Knapsack",
    "Taint",
    "Scrote",
    "Flapjack",
    "Elrond",
    "Pop Pop",
    "Grandma",
    "Screedle",
    "Grinch",
    "Skittletooth",
    "Scribbleface",
    "Coma",
    "Folk",
    "Scrub",
    "Twat",
    "Bitch",
    "Turd",
    "Splat",
    "Jizz",
    "Triplet",
    "Nasty",
    "Soundcloud",
    "Facetat",
    "Accountant",
    "Baby",
    "Merkin",
    "Skreep",
    "Fella",
    "Pube",
    "Gandalf",
    "Midget",
    "Charles",
    "Jesus",
    "Bastard",
    "Generic",
    "Interchangeable",
    "Tweet",
    "Tiktok",
    "Earwax",
    "Discharge",
    "Weakling",
    "Lannister",
    "Abomination",
    "Stem Cell",
    "Stillborn",
    "Creep Creep",
    "Failure",
    "Turkeyneck",
    "Dolla",
    "Tard",
    "Dropout",
    "Herpes",
    "Xanax Reference",
    "Cantspell",
    "Trope",
    "Meme",
    "Dipshit",
    "Stenchy",
    "Peepee",
    "Weenus",
    "Herbie",
    "Foreskin",
    "Fleep Fleep",
    "Skank",
    "Mange",
    "Pistol Starter",
    "Leper",
    "Fissure",
    "Wartbottom",
]

brand = [
    "Gucci",
    "G.E.D",
    "Blunts",
    "40 Oz",
    "Prada",
    "Mercedes",
    "Fellatio",
    "Sam's Choice",
    "Kmart",
    "Hilfiger",
    "Versace",
    "Goodwill",
    "Ferrari",
    "Vuitton",
    "Porsche",
    "Cartier",
    "Dior",
    "Triplet",
    "Maybach",
    "Killa",
    "Twitter",
    "Cannibal",
    "Pfizer",
    "Hasbro",
    "Milton Bradley",
    "Mattel",
    "Hooker",
    "Nissan",
]

headline = [
    "Squashes Beef With",
    "Starts Beef With",
    "Eats Beef With",
    "Slaps",
    "Disses",
    "Collaborates With",
    "Falls In Love With",
    "Publicly Fondles",
    "Performs Live With",
    "Hits #1 With",
]

headline2 = [
    "On Latest Single",
    "On Controversial New Single",
    "On Newest Hit Single",
    "On Latest Track",
]

def town_name():
    return f"{rc(townprefix)}{rc(townsuffix)}"

def rapname():
    return f"{rc(prefix)} {rc(suffix)}"

def rapheadline():
    return f"{rapname()} {rc(headline)} {rapname()} {rc(headline2)} '{rc(brand)} {rc(brand)}'"
